---
title: "Expanded NCBI Search"
author: "Stephen Synchronicity"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
always_allow_html: yes
header-includes:
   - \usepackage{dcolumn}
output: 
  html_document: 
    self_contained: yes
    css: C:\Users\Administrator\Documents\R\win-library\3.5\neuhwk\rmarkdown\templates\DA5030\resources\bootstrap.min.css
    highlight: zenburn
    keep_md: no
    theme: spacelab
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_folding: hide
---
```{r setup, include=FALSE}
# Knitr Options
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE, fig.align = 'center', fig.height = 5, fig.width = 7.5, tidy = TRUE, tidy.opts = list(width.cutoff = 80))
options(scipen = 12)
# Make reproducible
set.seed(1)
# Load packages
HDA::startPkgs(c("tidyverse","htmltools","magrittr","rentrez","printr"))
# # Attach dependencies
# rmarkdown::html_dependency_jquery()
# rmarkdown::html_dependency_bootstrap("spacelab")
# rmarkdown::html_dependency_jqueryui()
# # Use Chunk Titles to add Bold Headings to Chunks
# source("~/R/Scripts/addChunkTitles.R")
# rmd <- addChunkTitles(rstudioapi::getSourceEditorContext()$path)
# write(rmd,file=(rstudioapi::getSourceEditorContext()$path))
# # HTML to Latex
# source("~/R/Scripts/HTMLtoLatex.R")
# rmd <- HTMLtoLatex(rstudioapi::getSourceEditorContext()$path)
# write(rmd,file=(rstudioapi::getSourceEditorContext()$path))
```

```{r 'Google Scholar Query'}
paste(paste(c("mindfulness", "meditation"), collapse = " OR "), paste(c("education","elementary","student","grade","grader","middle School","high school","undergraduate","university","graduate","pedagogy","college","academic", "academia", "educational"), collapse = " OR "), paste(c("self-compassion scale", "self compassion scale"), collapse = " OR "), sep = " AND ")
```
```{r 'Form Expanded query'}
educ <- paste(c("education","elementary","student","grade","grader","middle School","high school","undergraduate","university","graduate","pedagogy","college","academic", "academia", "educational"),"[TIAB]",sep = "") %>% paste(collapse = " OR ")
qnot <- paste(c("HIV","Cancer","cancer"),sep="") %>% paste(collapse = " OR ")
outcome <- paste(c("Self Compassion Scale","Self-compassion scale","SCS","Compassion scale","Neff"),"[TIAB]",sep = "") %>% paste(collapse = " OR ")
tags$p("Query:")
(query2 <- paste0("mindfulness[TIAB] OR meditation[TIAB] OR meditation[MESH] AND ","(",educ,")"," AND ","2000:2018[EDAT]"," AND ","(",outcome,")"," NOT ","(",qnot,")"))
(ids <-  entrez_search(db = "pubmed", term=query2, sort="relevance", retmax = 1000, use_history = T))
```
```{r 'Extract info from Pubmed Query Result'}
summary_records <- list()
for (seq_start in seq(0,round(length(ids$ids),1),50)) {
recs <-  entrez_summary(db = "pubmed", web_history = ids$web_history, retmax = 50, retstart = seq_start)
summary_records <- append(recs, summary_records)
}
```
```{r 'Create Data Frame of Results'}
tags$h3("All Titles")
e_titles <- lapply(summary_records,FUN = extract_from_esummary,elements = c("title","authors")) %>% do.call("rbind",.) %>% as.data.frame %>% add_rownames(var = "ID") %>% setNames(nm = c("ID","Title")) %>% mutate_at(vars("Title"),funs(as.character)) #%>% DT::datatable()
```
```{r 'Fetch abstracts'}
fetchAbstracts <- function(id) {
  entrez_fetch(db = "pubmed", id = id, rettype = "abstract")
}
e_titles %<>% rowwise %>% mutate(Abstract = fetchAbstracts(ID))
```
```{r 'Auth Sheet'}
googlesheets::gs_auth(token = "~//R//husky_googlesheets_token.rds")
gs_sheet <- googlesheets::gs_url("https://docs.google.com/spreadsheets/d/1dq_9WL8PY3B8EGei3GdlKwxPfD1KlcegmC0QVfI70cI/edit#gid=1340687519")
```
```{r 'Put to GS for coding purposes'}
googlesheets::gs_edit_cells(gs_sheet, ws = "Expanded", input = e_titles, col_names = T)
```
```{r 'Retrieve from GS and Filter'}
e_titles <- googlesheets::gs_read(gs_sheet, ws = "Expanded")
e_titles %<>% filter(.[[4]] == T) %>% select(-4)
```
```{r 'Downloading Sorting'}
e_titles %<>% fix
e_titles_final <- e_titles
#Recreate e-titles in order to add authors
```
```{r 'Add Authors'}
e_titles_final$Author <- summary_records[as.character(e_titles_final$ID)] %>% purrr::map(.f = function(l){
  purrr::pluck(l,"authors",1,1)
})
```
```{r 'de Carvalho 2017 Students'}
#Students self-report of affect, emotion control, self-compassion, and mindfulness
(StuSCS <- c("Self-kindness 2.95 1.00 3.19 0.93 3.13 0.95 3.21 1.02", "Common-humanity 2.78 1.04 3.08 1.11 3.13 1.9 3.12 1.09", "Self-judgment 3.95 0.98 3.89 0.87 3.88 0.99 3.75 1.01", "Mindfulness 2.86 0.99 3.03 0.98 3.01 0.94 3.21 0.93") %>% str_split("\\s") %>% do.call("rbind", .) %>% as.data.frame  %>% mutate_at(vars(c(2:9)),funs(as.numeric(as.character(.)))) %>% column_to_rownames("V1") %>% setNames(c("ExpPreM","ExpPreSD","ExpPostM","ExpPostSD","ConPreM","ConPreSD","ConPostM","ConPostSD")))
(TeaSCS <- c("Self-kindness 3.08 0.75 3.69 0.76 2.81 0.77 2.86 0.72", "Self-judgment 2.91 0.59 2.84 0.81 2.80 0.55 2.94 0.34", "Common-humanity 3.23 0.80 3.59 0.48 2.86 0.69 3.11 0.71", "Mindfulness 3.40 0.60 3.60 0.64 3.14 0.38 3.00 0.38", "Isolation 2.60 0.87 2.38 0.66 2.93 0.79 2.89 0.13", "Over-identification 3.02 0.90 2.67 0.85 3.07 0.85 3.00 0.57") %>% str_split("\\s") %>% do.call("rbind", .) %>% as.data.frame  %>% mutate_at(vars(c(2:9)),funs(as.numeric(as.character(.)))) %>% column_to_rownames("V1") %>% setNames(c("ExpPreM","ExpPreSD","ExpPostM","ExpPostSD","ConPreM","ConPreSD","ConPostM","ConPostSD")))
#Reverese code negative categries
StuSCS[3,c(1,3,5,7)] %<>%  {6 - .}
TeaSCS[c(2,5,6),c(1,3,5,7)] %<>% {6 - .}
StuSCS %>% colMeans %>% googlesheets::gs_edit_cells(gs_sheet, ws = "FP Screen 2 SCS", input = ., anchor = "K13", byrow = T)
TeaSCS %>% colMeans%>% googlesheets::gs_edit_cells(gs_sheet, ws = "FP Screen 2 SCS", input = ., anchor = "K14", byrow = T)
```


```{r 'Barbosa eff size'}
readxl::read_xlsx(path = "Barbosa_Final.Data.MBSR.100309.xlsx") %>% names
```




